---
title: "Untitled"
output: html_document
date: "2024-04-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lme4)
library(emmeans)
library(ggridges)
library(gamm4)
library(MASS)
library(tidyverse)
```

# Import data

```{r}
# Import data
df <- read_csv("data/drm/export.csv") %>%
  mutate(across(where(is.character), as_factor),
         Date = as_date(as.character(Date), format = "%m/%d/%Y"))

# Get day of the year number, week, and month for some model fitting
df <- df %>%
  mutate(Day = yday(Date),
         Week = factor(week(Date)),
         Month = factor(month(Date)))

# Subset just 2023 surveys
df23 <- filter(df, year(Date) == "2023")

# Order Subregions from south to north
df23 <- df23 %>%
  mutate(Subregion = fct_relevel(Subregion, c("Tortugas--Dry Tortugas NP", "Marquesas", "Lower Keys", 
                                              "Middle Keys", "Mid-Upper Keys Transition", "Upper Keys",
                                              "Biscayne", "Broward-Miami", "South Palm Beach", 
                                              "North Palm Beach", "Martin")))

# Order Species alphabetically
df23 <- df23 %>%
  mutate(Species = factor(Species, levels = sort(levels(df$Species))))

# Create ordinal variables and factors for bleaching severity
df23 <- df23 %>%
  mutate(Bleaching2 = case_when((is.na(Bleaching) & !grepl("TRS", `Other Conditions`)) ~ 0,
                                Bleaching == "P" ~ 1,
                                Bleaching == "PB" ~ 2,
                                Bleaching == "BL" ~ 3,
                                ((Old + Recent) >= 100 & grepl("TRS", `Other Conditions`)) ~ 4),
         Bleaching3 = factor(case_match(Bleaching2, 
                                 0 ~ "Healthy",
                                 1 ~ "Pale",
                                 2 ~ "Partially Bleached",
                                 3 ~ "Bleached",
                                 4 ~ "Dead"),
                             levels = c("Healthy", "Pale", "Partially Bleached", "Bleached", "Dead")))

#### There are 45 corals listed with "TRS" but are blank for "Bleaching"... talk to Jennifer about these?
#### For now, remove these from analysis
df23 <- df23 %>%
  filter(!is.na(Bleaching2))

### There are corals with Width < 4 ... keep? or errors?
df23ss3 %>% filter(Width < 4)



# Import 2023 DHW data
dhw <- read_csv("data/dhw/dhw_processed.csv") %>%
  mutate(across(where(is.character), as_factor)) %>%
  rename(Date = date) %>%
  dplyr::select(Site, Date, dhw)

# Get DHW values for each DRM survey site on date surveyed
df23 <- left_join(df23, dhw, by = c("Site", "Date"))

# Create DHW bins
df23 <- df23 %>%
  mutate(dhw.bin = cut(dhw, breaks = c(0,4,8,12,16,20,24)))
```

# Survey information

```{r}
# How many total corals surveyed of each species?
sppcounts <- df23 %>%
  count(Species) %>%
  arrange(-n)

# How many sites per Subregion?
# How are reef Zones diff across Subregions?
df23 %>%
  distinct(Subregion, Site, Zone) %>%
  group_by(Subregion) %>%
  ggplot(aes(x = Subregion, fill = Zone)) +
  geom_bar(position = "stack") +
  scale_y_continuous(breaks = seq(0, 100, 10)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# How were 2023 surveys distributed across time and space?
surveys <- df23 %>%
  distinct(Subregion, Date, Site, dhw)

ggplot(surveys, aes(x = Date, y = Subregion, fill = Subregion)) +
  geom_density_ridges(alpha = 0.6, stat = "binline", bins = 20) +
  theme(legend.position = "none")

# How were surveys distributed across DHW accumulation?
ggplot(surveys, aes(x = dhw, y = Subregion, fill = Subregion)) +
  geom_density_ridges(alpha = 0.6, stat = "binline", bins = 20) +
  theme(legend.position = "none")
```

# Bleaching

```{r}
# Did overall bleaching severity change over time?

## Fit GAMM for overall bleaching level over time within each Subregion
mod <- gam(Bleaching2 ~ s(Day, by = Subregion), data = df23)
res <- emmeans(mod, specs = "Day", by = "Subregion", at = list(Day = seq(167, 318, 1)))
# Plot 
df23 %>%
  distinct(Subregion, Day, Date) %>%
  arrange(Subregion, Date) %>%
  left_join(as.tibble(res)) %>%
  mutate(Date = as.Date(Day, origin = as.Date("2024-01-01"))) %>%
  ggplot(aes(x = Date, y = emmean, color = Subregion, group = Subregion)) +
  geom_line() +
  ylim(0, 3)

```

# Subset data for bleaching analysis
```{r}
df23ss <- df23 #%>%
  # Subset mid-August to end of September? (stable peak of bleaching to allow comparing across Subregions, e.g. Marquesas was in Oct. only)
  #filter(Date >= "2023-08-15" & Date <= "2023-09-30")

# Filter out dead corals from causes OTHER than bleaching ("TRS")
df23ss <- df23ss %>%
  filter(((Old + Recent) < 100 | grepl("TRS", `Other Conditions`)))

# Subset just species with >=3 observations per Subregion
abund_spp2 <- df23ss %>%
  group_by(Subregion) %>%
  count(Species) %>%
  filter(n >= 3)

df23ss <- df23ss %>%
  right_join(abund_spp2) %>%               # Apply filter
  mutate(Species = droplevels(Species))
```

# - [ ] Bleaching severity by species (in relation to location and DHW). which species more/less bleached
```{r}
# Average bleaching severity level (0-4) of each species in each subregion
mod <- lmerTest::lmer(Bleaching2 ~ Species * Subregion + (1|Site) + (1|Month), data = df23ss)
anova(mod)

emm <- emmeans(mod, specs = "Species", by = "Subregion")

bleaching_by_region_all <- as.tibble(emm) %>%
  ggplot(aes(x = Subregion, y = emmean, color = Species, group = Species)) +
  geom_point() +
  geom_line() +
  facet_wrap(~Species) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

bleaching_by_region_all %+% filter(as.tibble(emm), Species %in% sppcounts$Species[which(sppcounts$n > 75)])
```

```{r}
# Probability of each bleaching level by species as a function of DHW (ordinal regression)
#https://tdunn.ca/posts/2020-03-15-ordinal-regression-in-r-part-1/


# Subset corals further for species with enough data to model an interaction effect with Species*dhw
df23ss2 <- df23ss %>%
  filter(Species %in% sppcounts$Species[which(sppcounts$n > 75)])

# Probability of each bleaching level by species as a function of DHW
m <- polr(Bleaching3 ~ Species * dhw, data = df23ss2, Hess = TRUE, model = TRUE)

res <- emmeans(m, specs = c("dhw", "Bleaching3"), by = "Species", mode = "prob", at = list(dhw = seq(0, 24, 1)))

bleachcat_by_dhw <- as.tibble(res) %>%
  ggplot(aes(x = dhw, y = prob, color = Bleaching3)) +
  geom_line() +
  facet_wrap(~Species) +
  xlim(0,24)

##### GOOD
bleachcat_by_dhw %+% filter(as.tibble(res), Species %in% sppcounts$Species[which(sppcounts$n > 75)])
#####

thresh <- as.tibble(res) %>%
  filter(Species %in% sppcounts$Species[which(sppcounts$n > 100)]) %>%
  filter(Bleaching3 == "Bleached") %>%
  group_by(Species) %>%
  summarize(thresh = min(dhw[prob > 0.5])) %>%
  mutate(Species = fct_reorder(Species, thresh))

##### BETTER
as.tibble(res) %>%
  filter(Species %in% sppcounts$Species[which(sppcounts$n > 100)]) %>%
  mutate(Species = factor(Species, levels = levels(thresh$Species))) %>%
  ggplot(aes(x = dhw, y = prob, color = Bleaching3)) +
  geom_line() + 
  facet_wrap(~Species) +
  geom_vline(data = thresh, aes(xintercept = thresh), lty = 2, lwd = 0.25)
#####

## Calculate proportion of colonies fully bleached or Dead at diff. DHW levels
res2 <- emmeans(m, specs = c("dhw", "Bleaching3"), by = "Species", mode = "prob", at = list(dhw = c(10, 20)))

BlDead <- as.tibble(res2) %>%
  filter(Species %in% sppcounts$Species[which(sppcounts$n > 75)],
         Bleaching3 %in% c("Bleached", "Dead")) %>%
  group_by(Species, dhw) %>%
  summarize(BlDead = sum(prob))

ranks <- BlDead %>%
  group_by(Species) %>%
  summarize(meanBlDead = BlDead[dhw==20]) %>%
  #filter(dhw == 10) %>%
  arrange(-meanBlDead) %>%
  mutate(Species = fct_reorder(Species, -meanBlDead))

BlDead %>%
  mutate(Species = factor(Species, levels = levels(ranks$Species))) %>%
  ggplot(aes(x = Species, y = BlDead, color = factor(dhw))) +
  geom_point() +
  #geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Show just some spp of interest
as.tibble(res) %>%
  filter(Species %in% c("AAGA", "ACER", "CNAT", "DLAB", "DSTO", "OFAV", "MCAV", "SSID")) %>%
  filter(Bleaching3 == "Bleached") %>%
  ggplot(aes(x = dhw, y = prob, color = Species)) +
  geom_line()

# Look at data for individual species
df23ss2 %>%
  filter(Species == "ACER") %>%
  ggplot(aes(x = dhw.bin, fill = Bleaching3)) +
  geom_bar()

# Where was healthy ACER observed with 8-12 DHW?
test <- df23ss2 %>%
  filter(Species == "ACER", Bleaching3 == "Healthy", dhw > 8)
View(test)
y1069 <- df23ss2 %>% filter(Site == "Y1069")
View(y1069)
```

```{r}
ggplot(df23ss, aes(x = dhw, y = Bleaching2, color = Species)) +
  geom_point(alpha = 0.1) +
  facet_wrap(~Species)

# Bleaching as a function of DHW bin for each Species
mod <- lmerTest::lmer(Bleaching2 ~ Species * dhw.bin + (1|Site), data = df23ss)
anova(mod)

emm <- emmeans(mod, specs = c("Species", "dhw.bin"), at = list(dhw.bin = levels(df23ss$dhw.bin)))

as.tibble(emm) %>%
  ggplot(aes(x = dhw.bin, y = emmean, color = Species, group = Species)) +
  geom_point() +
  geom_line() +
  #facet_wrap(~Species) +
  ylim(0, 4)



# Need to try some binomial modeling with BL as response (1=BL, 0=notBL) to model proportion of colonies bleached at various locations and dhw levels....

mod <- glm((Bleaching2 >= 3) ~ Species * dhw, data = df23ss, family = "binomial")
emm <- emmeans(mod, specs = c("Species", "dhw"), at = list(dhw = seq(0,24,1)), mode = "prob", type = "response")
as.tibble(emm) %>%
  filter(Species %in% sppcounts$Species[which(sppcounts$n > 75)]) %>%
  ggplot(aes(x = dhw, y = response, color = Species, group = Species)) +
  geom_line()# +
  #facet_wrap(~Species)
```




```{r}
# - [ ] Variability in bleaching among individuals within a species 
### which spp have the most variability among individuals?

var <- df23ss %>%
  group_by(Site, Latitude, Longitude, Species, Subregion, Zone) %>%
  summarize(n = n(),
            bleachvar = var(Bleaching2),
            max = max(Bleaching2)) %>%
  filter(n >= 10, max == 3, bleachvar > 0)

ggplot(var, aes(x = Species, y = bleachvar)) +
  geom_violin(scale = "width", draw_quantiles = 0.5) +
  geom_jitter(aes(color = Subregion), width = 0.2)

## where do tol. and sens. individuals co-occur?

var %>% filter(Species == "MCAV") %>%
  ggplot(aes(x = Longitude, y = Latitude)) +
  geom_point(aes(color = bleachvar))


#### Barplots of bleaching categories for each species
filter(df23ss, Species == "SSID") %>%
  ggplot(aes(x = Week, fill = factor(Bleaching2))) +
  geom_bar(position = "fill") +
  facet_grid(Subregion~"")
```

```{r}
#  - [ ] Where are heat-tolerant individuals? i.e., most non-bleached individuals rel. to DHW

# Need to do this on the colony-level...
######## THIS IS REALLY GOOD VVVVVVVVVV
df23ss2 <- df23ss %>% 
  #filter(Subregion %in% c("Lower Keys", "Upper Keys", "Biscayne")) %>%
  #filter(Species %in% c("MCAV", "AAGA", "PPOR")) %>%
  mutate(Site = droplevels(Site)) %>%
  mutate(BL = Bleaching2 > 2)
mod <- glmer(BL ~ dhw * Depth + (dhw*Depth|Species) + (1|Week), ### what about (1|Site) to control for dhw and depth?
             family = "binomial", data = df23ss2,
             nAGQ = 0, control = glmerControl(optimizer = "nloptwrap"))

anova(mod)

test <- tibble(df23ss2, .resid = residuals(mod, type = "response"))
test2 <- test %>% group_by(Site, Longitude, Latitude) %>%
  summarize(meanResid = mean(.resid)) %>%
  arrange(meanResid)
# negative values indicate less bleaching than predicted based on dhw, depth, and species...

# Plot sites that bleached more/less than expected
myPlot <- ggplot(test2, aes(x = Longitude, y = Latitude, color = sign(meanResid) * meanResid^2,
                            size = meanResid^2)) +
  geom_point(alpha = 0.4) +
  scale_color_gradient2()
myPlot

myPlot + xlim(-82, -81) + ylim(24.2, 24.8)
myPlot + xlim(-81, -80) + ylim(24.5, 25.5)
myPlot + xlim(-80.3, -80) + ylim(25.5, 27) +
  geom_hline(yintercept = c(25.7588, 26.0923, 26.257518, 26.54476, 26.77238))


myPlot +
  geom_hline(yintercept = c(25.7588, 26.0923, 26.54476, 26.77238))



#### Plot on map?
# Download satellite map for Florida
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
world <- ne_countries(scale = "large", returnclass = "sf")
# Plot map
set.seed(10)
fig1a <- #ggmap(map_fl, extent = "panel") +
  ggplot(data = world) +
  geom_sf(lwd = 0, fill = "gray70") +
  coord_sf(xlim = c(-83.2, -79.5), ylim = c(23.7, 26.9), expand = FALSE) +
  scale_fill_manual(values = alpha(c("#F8766D", "#B79F00", "#00BA38", 
                                     "#00BFC4", "#619CFF", "#F564E3"), 0.7)) +
  # scale_y_continuous(breaks = c(24, 25, 26), labels = c(24, 25, 26)) +
  # scale_x_continuous(breaks = c(-82, -81, -80), labels = c(-82, -81, -80)) +
  theme(legend.position = "none") +
  theme(text = element_text(size = 10),
        panel.background = element_blank(),
        panel.border = element_rect(colour = "black", fill=NA)) +
  labs(y = "Latitude", x = "Longitude")
fig1a

hihihi <- fig1a +
  geom_point(data = test2, aes(x = Longitude, y = Latitude, fill = sign(meanResid) * meanResid^2,
                            size = meanResid^2), alpha = 0.5, stroke = 0.1, pch = 21) +
  scale_fill_gradient2(low = "red", mid = NA, high = "blue")
hihihi 
hihihi + coord_sf(xlim = c(-82, -80.8), ylim = c(24.4, 24.8))
hihihi + coord_sf(xlim = c(-81, -80), ylim = c(24.6, 25.5))
hihihi + coord_sf(xlim = c(-80.2, -80), ylim = c(25.5, 27)) +
  geom_hline(yintercept = c(25.7588, 26.0923, 26.257518, 26.54476, 26.77238)) +theme(aspect.ratio = 2)

# Is molasses an outlier as a site that did much better than expected?
#Y3042
y3042 <- df23 %>%
  filter(Site == "Y3042")
```


```{r}
# - [ ] Are juveniles doing better (less bleaching) than larger adult colonies for any species?

# Model bleaching severity by species and size class
df23ss3 <- df23ss2 %>%
  mutate(sizeclass = case_when(Width <= 7 & (Old + Recent) <= 10 ~ "juv",
                               TRUE ~ "adult")) %>%
  filter(dhw > 10)
mod <- glmer(BL ~ sizeclass * Species + (1|Site) + (1|Week), 
             family = "binomial", data = df23ss3, 
             nAGQ = 0, control = glmerControl(optimizer = "nloptwrap"))

anova(mod)

emm <- emmeans(mod, specs = c("Species", "sizeclass"), type = "response")
as.tibble(emm) %>%
  ggplot(aes(x = sizeclass, y = prob)) +
  facet_wrap(~Species, scales = "free") +
  geom_point() +
  geom_errorbar(aes(ymin = prob - SE, ymax = prob + SE))

stats <- rbind(contrast(emm, "pairwise", by = "Species")) %>%
  as.tibble() %>%
  arrange(p.value) %>%
  print(n = nrow(.))

sigspp <- stats %>%
  filter(p.value < 0.05)

as.tibble(emm) %>%
  filter(Species %in% sigspp$Species) %>%
  ggplot(aes(x = sizeclass, y = prob)) +
  facet_wrap(~Species, scales ="free") +
  geom_point() +
  geom_errorbar(aes(ymin = prob - SE, ymax = prob + SE))


# Size of BL vs UNBL MCAV
mcav <- df23ss2 %>% filter(Species == "PSTR")
mod <- glmer(BL ~ log(Width) * dhw + (1|Site), family = "binomial", data = mcav)
res <- emmeans(mod, specs = c("Width", "dhw"), at = list(Width = seq(min(mcav$Width),max(mcav$Width),2), dhw = 15), type = "response")
res
ggplot(as.tibble(res), aes(x = Width, y = prob)) +
  geom_line(aes(color = dhw, group = dhw)) +
  geom_ribbon(aes(ymin = asymp.LCL, ymax = asymp.UCL), alpha = 0.1)

ggplot(mcav, aes(x = BL, y = log(Width))) +
  geom_violin() +
  geom_jitter(width = 0.1)


ggplot(mcav, aes(x = cut(log(Width), 5), fill = BL)) +
  geom_bar(position = "fill")

range(mcav$Width)


### all species?
df23ss3 <- filter(df23ss2, Species %in% sppcounts$Species[1:10])
mod <- glmer(BL ~ Species * Width + dhw + (1|Site), family = "binomial", data = df23ss3,
             nAGQ = 0, control = glmerControl(optimizer = "nloptwrap"))
anova(mod)
res <- emmeans(mod, specs = c("Width", "Species", "dhw"), 
               at = list(Width = seq(4,500,2), dhw = 15), type = "response")
sizeranges <- df23ss3 %>% group_by(Species) %>% summarize(min = min(Width), max = max(Width))
sizeranges
res
ggplot(as.tibble(res), aes(x = Width, y = prob)) +
  geom_line(aes(color = Species, group = Species)) +
  geom_ribbon(aes(ymin = asymp.LCL, ymax = asymp.UCL), alpha = 0.1)

df23ss3 %>% filter(Width < 4)
```
    

    
