---
title: "Cross-year comparisons"
author: "R. Cunning"
date: "2024-05-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lme4)
library(emmeans)
library(tidyverse)
# Download satellite map for Florida
world <- rnaturalearth::ne_countries(scale = "large", returnclass = "sf")
```

# Import all data (2014, 2015, 2023)
```{r}
# Load all data from 2014, 2015, and 2023
# QC'd by year
load("output/2014.RData")
load("output/2015.RData")
load("output/2023.RData")
df23 <- df23 %>% rename(Depth = EndDepth, Transect = TransectNum)
all0 <- bind_rows(
  `2014` = df14,
  `2015` = df15,
  `2023` = df23,
  .id = "year"
) %>%
  mutate(dhw.bin = cut(dhw, breaks = seq(0, 21, 3)))

# Aggregate Agaricia spp. other than AAGA, Mycetophyllia spp., Isophyllia spp., Oculina spp., Solenastrea spp., Scolymia spp.
all0 <- all0 %>%
  mutate(Species = case_when(Species %in% c("AFRA", "AGAR", "AGRA", "AHUM", "ALAM") ~ "AGAR",
                             Species %in% c("MALI", "MLAM", "MYCE") ~ "MYCE",  #, "MFER"
                             Species %in% c("IRIG", "ISIN", "ISOP") ~ "ISOP",
                             Species %in% c("OCUL", "ODIF") ~ "OCUL",
                             Species %in% c("SHYA", "SBOU") ~ "SOLE",
                             #Species %in% c("SCOL", "SCUB", "SLAC", "SWEL") ~ "SCOL",
                             TRUE ~ Species)) %>%
  drop_na(Species)

# Keep only those species observed at least 10 times per year
# Filter1 -- working well but too strict?
# spps <- all0 %>%
#   count(Species, year) %>%
#   group_by(Species) %>%
#   summarize(minn = min(n), nyear = n()) %>%
#   filter(minn >= 10)
# allf <- all0 %>%
#   filter(Species %in% spps$Species)
# Try alternate filter -- bad results
# allf <- all0 %>%
#   group_by(Species, year) %>%
#   filter(n() >= 10) %>%         # Species must have been counted at least 10 times within a year
#   group_by(Species) %>%
#   filter(n_distinct(year) == 3) %>%     # Species must have been counted (at least 10 times) in at least 2 years
#   ungroup()
# Try another alternate filter using dhw.bins
allf <- all0 %>%
  group_by(Species, year, dhw.bin) %>%
  filter(n() > 3)

## Group data at species+site-level to fit group-level models instead of subject-level models -- fits faster
allg <- allf %>%
  group_by(year, Week2, Subregion, Site, dhw.bin, Species) %>%
  summarize(BL = sum(Bleaching2 > 1),
            NB = sum(Bleaching2 <= 1)) %>%
  ungroup()
```

# Overall bleaching severity in 2023
```{r}
# Get percent of colonies surveyed that were bleached at each site 
pctbl23 <- df23 %>%
  #filter(Date >= as.Date("2023-08-01"), Date <= as.Date("2023-09-30")) %>%
  group_by(Site, Subregion, Latitude, Longitude, Week2) %>%
  summarize(BL = sum(Bleaching2 > 1),
            NB = sum(Bleaching2 <= 1),
            pctbl = BL / (BL + NB)) %>%
  ungroup()

# Model proportion of bleached colonies in each subregion in each 2-week window of survey
mod <- glm(cbind(BL, NB) ~ Subregion + Week2, family = "binomial", data = pctbl23)

# Predict proportion of bleached colonies in each Subregion at weeks 34-35 (Week2 = "(33,35]" => (August 20-September 2))) = peak of bleaching
## Get these Subregion probabilities at this time on the log-odds scale (NOT type = 'response')
res <- emmeans(mod, specs = c("Subregion"), at = list(Week2 = factor("(33,35]")))

logit2prob <- function(logit){
  odds <- exp(logit)
  prob <- odds / (1 + odds)
  return(prob)
}

# Get residuals for each Site at the time it was surveyed (e.g., difference from Subregion mean at time surveyed)...
# ...and then add these residuals to the Subregion's predicted bleaching probability for Weeks 34-35 (peak of bleaching)
# ...to get predicted bleaching severity at that site, if it had been surveyed at peak of bleaching
pctbl23.adj <- pctbl23 %>%
  # Get residuals on the 'working' /logit scale
  mutate(resid = residuals(mod, type = "working")) %>%
  # Join site residuals with logit means for Subregion at weeks 34-35
  left_join(as_tibble(res)) %>%
  # Add residuals to logit mean for Subregion weeks 34-35, then convert to probability scale
  mutate(adj = emmean + resid,
         ## Function to convert logit to probability
         adjprob = exp(adj) / (1 + exp(adj)))

# Plot on map
(myplot <- ggplot(data = pctbl23.adj) +
  geom_sf(data = world, lwd = 0, fill = "gray70") +
  geom_sf(data = my_hull) +
  coord_sf(xlim = c(-83.2, -79.8), ylim = c(24.3, 27.3), expand = FALSE) +
  geom_point(aes(x = Longitude, y = Latitude, fill = adjprob), 
             alpha = 0.6, stroke = 0.05, pch = 21, height = 0.1, width = 0.1) +
  
  # scale_fill_gradient2(high = "red", mid = NA, low = "blue", midpoint = 0.5,
  #                      limits = c(0, 1)) +
  scale_fill_distiller(palette = "Spectral", limits = c(0, 1)) +
  #theme(legend.position = "none") +
  theme(text = element_text(size = 10),
        axis.title = element_blank(),
        panel.background = element_rect(fill = "white"),
        panel.border = element_rect(colour = "black", fill=NA),
        panel.grid = element_blank()))

# Change order of points to deal with overplotting
### Less bleaching plotted on top
myplot %+% arrange(pctbl23.adj, -adjprob)
### More bleaching plotted on top
myplot %+% arrange(pctbl23.adj, adjprob)

# Interpolate surface?
# https://geobgu.xyz/r/spatial-interpolation-of-point-data.html

# create raster object that is just the reef area?
sites23 <- pctbl23.adj %>%
  distinct(Site, Longitude, Latitude, adjprob)
library(sf)
pts1 <- st_as_sf(x = sites23, coords = c('Longitude', 'Latitude'))
my_hull <- st_convex_hull(st_union(pts1))
my_hull <- st_concave_hull(st_union(pts1), ratio = 0.1)
my_hull <- my_hull %>% st_set_crs(4326)
plot(my_hull)
my_buff <- st_buffer(st_union(pts1), 0.05)
plot(my_buff)
my_buff <- my_buff %>% st_set_crs(4326)


library(gstat)
g = gstat(formula = adjprob ~ 1, data = sites23)
z = predict(g, my_hull)

# Initialize a raster layer
ras <- raster(ext)

# Set the resolution to be
res(ras) <- c(cell_size, cell_size)
ras[] <- 0

# Project the raster
projection(ras) <- CRS("+init=epsg:3857")

# Create interactive map
mapview(station) + mapview(ras)
```

# Species differences in bleaching severity in 2023

```{r}

```

# Glimmers of hope

### Overall bleaching severity by DHWs in 2023 vs. 2014 and 2015

```{r bleaching_by_dhw.bin_across_years}
# Will it work if species is a random factor instead of fixed? YES!!!
# overall.bleach.mod <- glmer(cbind(BL, NB) ~ year * dhw.bin + (dhw.bin+year|Species), 
#            family = "binomial", data = allg)
# overall.bleach.res <- emmeans(overall.bleach.mod, specs = c("dhw.bin", "year"), 
#                               type = "response", rg.limit = 15000)
# as.tibble(overall.bleach.res) %>%
#   ggplot(aes(x = dhw.bin, y = prob, color = year, group = year)) +
#   geom_point() +
#   geom_ribbon(aes(ymin = asymp.LCL, ymax = asymp.UCL), lwd = 0, alpha = 0.2) +
#   geom_line()

### NEW: try with Week2 to be able to adjust for that
# dhw.bin.mod <- glmer(cbind(BL, NB) ~ dhw.bin * year * Week2 + (dhw.bin+year|Species),
#                        family = "binomial", data = allg)
## ^^ above model formulation has nonEst for 2023 0-3 and 6-9 DHW. Why?
# dhw.bin.mod <- glmer(cbind(BL, NB) ~ dhw.bin * year + year:Week2 + (1|Species),
#                        family = "binomial", data = allg)
###^^ This model works
dhw.bin.mod <- glmer(cbind(BL, NB) ~ dhw.bin * year + year:Week2 + (dhw.bin+year|Species),  
                     family = "binomial", data = allg, verbose = TRUE,
                     nAGQ=0, control=glmerControl(optimizer = "nloptwrap"))
#^^^ but is this one ^^ better? ???: YES
##change dhw.bin+year to dhw.bin*year in random slopes???: doesn't change much, takes longer to fit
dhw.bin.res <- emmeans(dhw.bin.mod, specs = c("dhw.bin", "year", "Week2"), 
                       rg.limit = 20000, type = "response")
# THIS IS IT ^^^
# Get emmeans for just the specific 2-week windows of interest in each year (corresp. to max. bleaching)
dhw.bin.res2 <- subset(dhw.bin.res,
  (year == "2014" & Week2 == "(36,38]") |
  (year == "2015" & Week2 == "(36,38]") |
  (year == "2023" & Week2 == "(33,35]")
)
as.tibble(dhw.bin.res2) %>%
  ggplot(aes(x = dhw.bin, y = prob, color = year, group = year)) +
  geom_point() +
  geom_ribbon(aes(ymin = asymp.LCL, ymax = asymp.UCL), lwd = 0, alpha = 0.2) +
  geom_line() +
  scale_y_continuous(limits = c(0, 1), expand = c(0, 0), breaks = seq(0, 1, 0.1)) +
  theme(legend.position = c(0.8, 0.25)) +
  labs(x = "DHWs", y = "Probability of bleaching")
# THIS IS IT ^^^

```

## Species-specific bleaching severity by DHWs in 2023 vs. 2014 and 2015

```{r SPECIES_diffs_by_dhwbin_by_year}
# Fit a singular model for bleaching susceptibility by Species, DHW.bin, and year, to look at how bleaching susceptibility differs by year

# Fit regression for PB or worse
dhw.bin.sp.mod <- glm(cbind(BL, NB) ~ year * Species * dhw.bin + year:Week2, family = "binomial", data = allg)
# Get fitted values across dhw
dhw.bin.sp.res <- emmeans(dhw.bin.sp.mod, specs = c("Species", "dhw.bin", "year", "Week2"), 
               rg.limit = 20000, type = "response")

# Get emmeans for just the specific 2-week windows of interest in each year (corresp. to max. bleaching)
dhw.bin.sp.res2 <- subset(dhw.bin.sp.res,
  (year == "2014" & Week2 == "(36,38]") |
  (year == "2015" & Week2 == "(36,38]") |
  (year == "2023" & Week2 == "(33,35]")
)
mybleach <- as.tibble(dhw.bin.sp.res2)
# Plot
allplots <- as.tibble(dhw.bin.sp.res2) %>%
  ggplot(aes(x = dhw.bin, y = prob, color = year, group = year)) +
  geom_point(position = position_dodge(width = 0.25), size = 0.5) +
  geom_line(position = position_dodge(width = 0.25)) +
  geom_errorbar(aes(ymin = prob - SE, ymax = prob + SE), width = 0.1,
                position = position_dodge(width = 0.25)) +
  facet_wrap(~Species) +
  ylim(0,1)
allplots

# For some reason the output is better when MFOR and SCUB are present in the data? Not sure why.
# MYCE (aggregated) was coming out as significant before but now it's not. something about adding MFER to the aggregation?
### Yes, it's MFER... when included with MYCE, MYCE has no sig diffs, but quite sig without the added MFER? MFER is all bleached, and all 

# Statistically compare years for each Species and dhw.bin level (only look at 3-6 and 6-9 dhw, where we have data from all years)
dhw.bin.sp.res3 <- subset(dhw.bin.sp.res2, dhw.bin %in% c("(3,6]", "(6,9]"))
dhw.bin.sp.tests <- rbind(pairs(dhw.bin.sp.res3, specs = "year", by = c("Species", "dhw.bin")), adjust = "fdr")
dhw.bin.sp.sig <- as.tibble(dhw.bin.sp.tests) %>%
  filter(p.value < 0.05)

dhw.bin.sp.sigres <- as.tibble(dhw.bin.sp.res2) %>%
  filter(Species %in% dhw.bin.sp.sig$Species)

# Plot just species with sig diffs btw years
allplots %+% dhw.bin.sp.sigres


# Sanity checks
# ## Simple proportions as a santiy check
# all0 %>%
#   drop_na(dhw.bin) %>%
#   group_by(year, Species, dhw.bin) %>%
#   summarize(pctbl = sum(Bleaching2 > 1) / n()) %>%
#   ggplot(aes(x = dhw.bin, y = pctbl, color = year, group = year)) +
#   geom_point() +
#   geom_line() +
#   facet_wrap(~Species)
# 
# # MYCE sanity check
# all0 %>% filter(Species == "MYCE") %>%
#   ggplot(aes(x = dhw.bin, fill = Bleaching3)) +
#   geom_bar(position = "stack") +
#   facet_wrap(~year)
```


```{r}
# Look at changes in avg coral density --- correlate w/changes in bleaching?
# Need zero-inflated Poisson regression?
dens <- all0 %>%
  ungroup() %>%
  # Count number of colonies of each species per transect
  count(year, Species, Site, Transect, Subregion) %>%
  # Add zeros for all species not counted on a transect
  complete(Species, nesting(year, Site, Transect, Subregion), fill = list(n = 0)) %>%
  # Filter transect 3 and 4 data -- only select species recorded 
  filter(Transect %in% c(1, 2) |
         Transect %in% c(3, 4) & Species %in% c("CNAT", "DSTO", "DLAB", "MMEA", "MANG",
                                                "MALI", "MFER", "MLAM", "PCLI", "PSTR")) %>%
  # SUBSET FOR FASTER MODELING
  group_by(Species, year) %>%
  filter(sum(n>0) > 10)
  
# ggplot(dens, aes(x = n)) +
#   geom_histogram() +
#   facet_wrap(~Species, scales = "free")

# library(pscl)
# m1 <- zeroinfl(n ~ Species + year | persons, data = zinb)

mod_1 <- glmer(n ~ Species * year + (Species|Subregion), data = dens, family = "poisson",
               verbose = TRUE, nAGQ=0, control=glmerControl(optCtrl=list(maxfun=100))) 
anova(mod_1)

res <- emmeans(mod_1, specs = c("Species", "year"), type = "response")

as.tibble(res) %>%
  ggplot(aes(x = year, y = rate)) +
  geom_point() + #aes(color = Subregion)
  geom_errorbar(aes(ymin = rate - SE, ymax = rate + SE)) +
  geom_line(aes(group = 1)) + #aes(group = Subregion, color = Subregion
  facet_wrap(~Species, scales = "free_y")

mydens <- as.tibble(res)
```

```{r}
# Get bleaching at 6-9 DHW
mybleach69 <- filter(mybleach, dhw.bin == "(6,9]")
myfun <- full_join(mydens, mybleach69, by = c("Species", "year"))

# any sig change over years in bleaching at 6-9dhw?
res3 <- subset(res2, dhw.bin %in% c("(6,9]"))
out <- rbind(pairs(res3, specs = "year", by = c("Species"), adjust = "fdr"))
sigbleach <- as.tibble(out) %>% filter(p.value < 0.05)

# any sig change over years in density?
outt <- rbind(pairs(res, specs = "year", by = "Species", adjust = "fdr"))
sigdens <- as.tibble(outt) %>% filter(p.value < 0.05)

# Plot species that had sig change in bleach OR sig change in dens
myfun %>%
  filter(Species %in% dhw.bin.sp.sig$Species) %>% # # | Species %in% sigdens$Species) %>%
  ggplot(aes(x = rate, y = prob)) +
  geom_point(aes(shape = year, color = year), size = 3) +
  geom_errorbar(aes(xmin = rate - SE.x, xmax = rate + SE.x)) +
  geom_errorbar(aes(ymin = prob - SE.y, ymax = prob + SE.y)) +
  geom_path(arrow = arrow(length = unit(1, "mm"))) +
  #geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~Species, scales = "free")
```


# Size diffs

## 2023 and possibly 2014 and 2015

```{r}

```



# Not to include?

## Bleaching by subregion across years

```{r regional_bleaching_vs_dhw_by_year_modeledalltogether}
# Model bleaching severity by subregion across years
### (This replicates what was done individually by year and then combined -- use THIS.)

subregion.mod <- glmer(cbind(BL, NB) ~ Subregion * year * Week2 + (1|Species),
                       family = "binomial", data = allg)

# Get fitted values across dhw
subregion.res <- emmeans(subregion.mod, specs = c("Subregion", "year", "Week2"), 
                         rg.limit = 20000, type = "response")

# Get emmeans for just the specific 2-week windows of interest in each year (corresp. to max. bleaching)
subregion.res2 <- subset(subregion.res,
  (year == "2014" & Week2 == "(36,38]") |
  (year == "2015" & Week2 == "(36,38]") |
  (year == "2023" & Week2 == "(33,35]")
)

as.tibble(subregion.res2) %>%
  ggplot(aes(x =))

regional <- bind_rows(
  `2014` = regional14,
  `2015` = regional15,
  `2023` = regional23,
  .id = "year"
)

as.tibble(subregion.res2) %>%
  left_join(regional, by = c("Subregion", "year")) %>%
  ggplot(aes(x = maxDHW, y = prob.y, shape = year, group = year, color = Subregion)) +
  geom_point(aes(color = Subregion, shape = year), size = 3) +
  geom_smooth(aes(group = year), method = "loess", span = 1.1, se = FALSE)

# This is good, but probably makes more sense to look at bleaching as a function of DHW across years. This is of more general interest than "Subregions"...
```

## Old code....

```{r, eval = F}
# Trying to get overall bleaching (avg across species) but emmeans are nonEst
m <- glm(cbind(BL, NB) ~ year * dhw.bin * Species, family = "binomial", data = allg)
res <- emmeans(m, specs = c("dhw.bin", "year"), type = "response", rg.limit = 15000)
as.tibble(res) %>%
  ggplot(aes(x = dhw.bin, y = prob, color = year, group = year)) +
  geom_point() +
  geom_line()

# Will it work if species is a random factor instead of fixed? YES!!!
library(lme4)
m <- glmer(cbind(BL, NB) ~ year * dhw.bin + (dhw.bin+year|Species), 
           family = "binomial", data = allg)
res <- emmeans(m, specs = c("dhw.bin", "year"), type = "response", rg.limit = 15000)
as.tibble(res) %>%
  ggplot(aes(x = dhw.bin, y = prob, color = year, group = year)) +
  geom_point() +
  geom_ribbon(aes(ymin = asymp.LCL, ymax = asymp.UCL), lwd = 0, alpha = 0.2) +
  geom_line()

### NEW: try with Week2 to be able to adjust for that
dhw.bin.mod <- glmer(cbind(BL, NB) ~ dhw.bin * year * Week2 + (dhw.bin+year|Species),
                       family = "binomial", data = allg)
dhw.bin.res <- emmeans(dhw.bin.mod, specs = c("dhw.bin", "year", "Week2"), 
                       rg.limit = 20000, type = "response")
# Get emmeans for just the specific 2-week windows of interest in each year (corresp. to max. bleaching)
dhw.bin.res2 <- subset(dhw.bin.res,
  (year == "2014" & Week2 == "(36,38]") |
  (year == "2015" & Week2 == "(36,38]") |
  (year == "2023" & Week2 == "(33,35]")
)
as.tibble(dhw.bin.res2) %>%
  ggplot(aes(x = dhw.bin, y = prob, color = year, group = year)) +
  geom_point() +
  geom_ribbon(aes(ymin = asymp.LCL, ymax = asymp.UCL), lwd = 0, alpha = 0.2) +
  geom_line()

```




```{r}
# Maps of site performance for each year
```



```{r, eval = F}
# Try random forests to find outlier sites or individuals?
load("output/2014.RData")
load("output/2015.RData")
load("output/2023.RData")
df23 <- df23 %>% rename(Depth = EndDepth)
all <- bind_rows(
  `2014` = df14,
  `2015` = df15,
  `2023` = df23,
  .id = "year"
)
library(randomForest)
data <- all %>%
  filter(Species %in% c("CNAT", "DLAB", "MCAV", "OANN", "OFAV", "PAST", "PSTR", "SSID")) %>%
  mutate(Bleaching4 = factor(case_when(Bleaching3 %in% c("Healthy", "Pale") ~ "Healthy",
                                Bleaching3 %in% c("Partially Bleached", "Bleached", "Dead") ~ "Bleached"))) %>%
  droplevels() %>%
  drop_na(year, Species, Depth, dhw) %>%
  group_by(Species) %>%
  filter(n() > 500) %>%
  droplevels()

# Run random forest classification with species, depth, and dhw as predictors
rf <- randomForest(Bleaching4~year+Species+Depth+dhw+Width, 
                   data = data, ntree = 5, do.trace = TRUE, proximity=TRUE)
print(rf)
rf$confusion

str(rf)

# Get rf model predictions for Bleaching4
data <- data %>%
  mutate(pred = rf$predicted)

# How accurate were predictions for each species?
data %>%
  drop_na(pred) %>%
  group_by(Species) %>%
  count(acc = pred == Bleaching4) %>%
  ggplot(aes(x = Species, y = n, fill = acc)) +
  geom_col(position= "fill")

# Can you get confidence?
str(rf)
score(rf)

data %>%
  drop_na(pred) %>%
  ggplot(aes(x = Species, fill = Bleaching4:pred)) +
  geom_bar(position = "fill")
  
  

# Which corals were predicted to be bleached, but were actually healthy?
outhealthy <- data %>%
  filter(pred == "Bleached", Bleaching4 == "Healthy") 

ggplot(outhealthy, aes(x = Longitude, y = Latitude)) +
  geom_point(color = "red", alpha = 0.005, pch = 20)

outhealthy %>%
  filter(Species == "OFAV") %>%
  ggplot(aes(x = Longitude, y = Latitude)) +
  geom_point(aes(color = Species))
```

```{r, eval = FALSE}
# Bleaching vs. dhw for each coral species by year -- binned dhw
# Data are from modeling data for each year separately, using the Week2 period at the peak of each year's bleaching
# Results are nearly (completely?) identical to a singular model fit with year and year:Week2... so use that because it also allows posthoc testing 
sppbleachprob14 <- readRDS(file = "output/sppbleachprob14.rds")
sppbleachprob15 <- readRDS(file = "output/sppbleachprob15.rds")
sppbleachprob23 <- readRDS(file = "output/sppbleachprob23.rds")

sppbleachprob <- bind_rows(`2014` = sppbleachprob14,
                           `2015` = sppbleachprob15,
                           `2023` = sppbleachprob23,
                           .id = "year")

sppbleachprob %>%
  ggplot(aes(x = dhw.bin, y = response, color = year, group = year)) +
  geom_point(position = position_dodge(width = 0.25), size = 0.5) +
  geom_line(position = position_dodge(width = 0.25)) +
  geom_errorbar(aes(ymin = response - SE, ymax = response + SE), width = 0.1,
                position = position_dodge(width = 0.25)) +
  facet_wrap(~Species) +
  ylim(0,1)
```


```{r, eval = F }
# I don't like this
# Overall Bleaching vs. dhw (all corals) by year
bleachprob14 <- readRDS(file = "output/bleachprob14.rds")
bleachprob15 <- readRDS(file = "output/bleachprob15.rds")
bleachprob23 <- readRDS(file = "output/bleachprob23.rds")

bleachprob <- bind_rows(`2014` = bleachprob14,
                        `2015` = bleachprob15,
                        `2023` = bleachprob23,
                        .id = "year")

ggplot(bleachprob, aes(x = dhw, y = response, color = year, group = year)) +
  geom_line() +
  geom_ribbon(aes(ymin = asymp.LCL, ymax = asymp.UCL), lwd = 0, alpha = 0.3) +
  scale_y_continuous(limits = c(0, 1))

# This is more or less the same thing as the breakdown by region above, but I think the regional one is more interesting

# What about doing this by dhw bins?
```

```{r regional_bleaching_vs_dhw_by_year, eval = FALSE}
# This was superseded by modeling this all together for all years instead of each year separately.
# Overall pct. bleaching vs. dhw (all corals) by Subregion for each year
## Subregion averages
load(file = "output/regional23.RData")
load(file = "output/regional14.RData")
load(file = "output/regional15.RData")

df <- bind_rows(`2014` = regional14, `2015` = regional15, `2023` = regional23, .id = "year")

ggplot(df, aes(x = maxDHW, y = prob)) +
  geom_point(aes(color = Subregion, shape = year), size = 3) +
  geom_smooth(aes(group = year), method = "loess", span = 1.1, se = FALSE)

## Why not do this for all sites? Probably would be too all over the place.
```









```{r, eval = F}

###trying to plot "adjusted" bleaching levels for each site -- adjusted for date surveyed
# Can we adjust pctbl for survey date and plot everything? (e.g., Marquesas were in Oct...)
df23.g <- df23 %>%
  group_by(Site, Subregion, Latitude, Longitude, Date, Week2, dhw) %>%
  summarize(BL = sum(Bleaching2 > 1),
            NB = sum(Bleaching2 <= 1))
mod <- glm(cbind(BL, NB) ~ dhw + Week2, family = "binomial", data = df23.g)
plot(mod, which = 1)

df23.g <- df23.g %>%
  ungroup() %>%
  mutate(resid = residuals(mod, type = "response")) %>%
  mutate(adj = (BL/(BL+NB)+resid))

hi <- broom::augment(mod, type.predict = "response") %>%
  mutate(resid2 = residuals(mod, type = "response"),
         adj = .fitted + resid2)

newdat <- tibble(
  Site = df23.g$Site,
  Subregion = df23.g$Subregion,
  pctbl = df23.g$BL / (df23.g$BL + df23.g$NB),
  dhw = df23.g$dhw,
  Longitude = df23.g$Longitude,
  Latitude = df23.g$Latitude,
  Week2 = factor("(33,35]")
)
newdat <- bind_cols(
  newdat,
  fit = predict(mod, type = "response", newdata = newdat)
)

# test <- df23.g %>%
#   mutate(.fitted = predict(mod, type = "response", newdata = newdat),
#          .resid = residuals(mod, type = "response"),
#          actual = BL / (BL + NB),
#          adj = .fitted + .resid)
# View(test)

ggplot(newdat) +
  geom_point(aes(x = Longitude, y = Latitude, fill = fit), 
             alpha = 0.5, stroke = 0.1, pch = 21) +
  scale_fill_gradient2(high = "red", mid = NA, low = "blue", midpoint = 0.5,
                       limits = c(0, 1))

hist(newdat$pctbl)

mod <- glm(cbind(BL, NB) ~ Subregion + Week2, family = "binomial", data = df23.g)
res <- emmeans(mod, specs = c("Subregion"), at = list(Week2 = factor("(33,35]")), type = "response")
test <- as.tibble(res) %>%
  right_join(df23.g) %>%
  mutate(resid = residuals(mod, type = "response"),
         actual = (BL/(BL+NB)),
         adj = actual + resid)

ggplot(test) +
  geom_point(aes(x = Longitude, y = Latitude, fill = actual), 
             alpha = 0.5, stroke = 0.1, pch = 21) +
  scale_fill_gradient2(high = "red", mid = NA, low = "blue", midpoint = 0.5,
                       limits = c(0, 1))
hist(test$adj)
```

