---
title: "Untitled"
output: html_document
date: "2024-05-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = TRUE)

library(lme4)
library(emmeans)
library(tidyverse)
```

### Import DRM data
```{r import_drm}
# Import DRM data
df0 <- read_csv("data/drm/export.csv") %>%
  mutate(across(where(is.character), as_factor),
         Date = as_date(as.character(Date), format = "%m/%d/%Y"))

# Get day of the year number, week, and month for some model fitting
df0 <- df0 %>%
  mutate(Day = yday(Date),
         Week = week(Date),
         Week2 = factor(cut(Week, breaks = seq(0,52,2))),
         Week = factor(Week),
         Month = factor(month(Date)),
         year = factor(year(Date)))

```

```{r}
# Aggregate Subregions which changed over time...
df <- df0 %>%
  mutate(Subregion = case_when(Subregion %in% c("Broward", "Broward-Miami") ~ "Broward-Miami",
                               Subregion %in% c("Deerfield", "Palm Beach",
                                                "South Palm Beach", "North Palm Beach") ~ "Palm Beach",
                               Subregion %in% c("Marquesas", "Marquesas-Tortugas Trans") ~ "Marquesas",
                               Subregion %in% c("Tortugas--Tortugas Bank", 
                                                "Tortugas--Dry Tortugas NP") ~ "Tortugas",
                               Subregion %in% c("Mid-Upper Keys Transition") ~ "Middle Keys",
                               TRUE ~ Subregion))


# Aggregate Agaricia spp. other than AAGA, Mycetophyllia spp., Isophyllia spp., Oculina spp., Solenastrea spp., Scolymia spp.
df <- df %>%
  mutate(Species = case_when(Species %in% c("AFRA", "AGAR", "AGRA", "AHUM", "ALAM") ~ "AGAR",
                             Species %in% c("MALI", "MLAM", "MYCE", "MFER") ~ "MYCE",  #, "MFER"
                             Species %in% c("IRIG", "ISIN", "ISOP") ~ "ISOP",
                             Species %in% c("OCUL", "ODIF") ~ "OCUL",
                             Species %in% c("SHYA", "SBOU") ~ "SOLE",
                             Species %in% c("SCOL", "SCUB", "SLAC", "SWEL") ~ "SCOL",
                             Species %in% c("OFAV", "OANN", "OFRA") ~ "ORBI",
                             TRUE ~ Species)) %>%
  drop_na(Species)


spp_to_include <- df %>%
  count(Species, year) %>%
  complete(Species, year, fill = list(n = 0)) %>%
  group_by(Species) %>%
  dplyr::filter(min(n) >= 10)  # 20 is a good cutoff

dens <- df %>%
  # Count number of colonies of each species per transect
  count(year, Species, Site, Transect, Subregion) %>%
  # Add zeros for all species not counted on a transect
  complete(Species, nesting(year, Site, Transect, Subregion), fill = list(n = 0)) %>%
  # SUBSET FOR FASTER MODELING
  filter(Species %in% spp_to_include$Species)
```

# Changes in density of each species over time
```{r}
mod_1 <- glmer(n ~ Species * year + (1|Subregion), data = dens, family = "poisson",
               verbose = TRUE, nAGQ=0, control=glmerControl(optimizer = "nloptwrap")) 
anova(mod_1)

res <- emmeans(mod_1, specs = c("Species", "year"), type = "response")

as.tibble(res) %>%
  ggplot(aes(x = year, y = rate)) +
  geom_point() + #aes(color = Subregion)
  geom_errorbar(aes(ymin = rate - SE, ymax = rate + SE)) +
  geom_line(aes(group = 1)) + #aes(group = Subregion, color = Subregion
  facet_wrap(~Species, scales = "free_y") +
  geom_vline(aes(xintercept = "2014")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

densres <- res
saveRDS(densres, file = "output/density.rds")
```

```{r}
# Look at size distribution over time
dff <- df %>%
  filter(Species %in% spp_to_include$Species)

ggplot(dff, aes(x = year, y = Width)) +
  scale_y_continuous(transform = "log", breaks = c(4, 16, 64, 256)) +
  geom_violin() +
  facet_wrap(~Species, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

# Changes in density of all corals by Subregion
```{r}
# Density of all corals
dens0 <- df %>%
  # Count number of colonies of each species per transect
  count(year, Site, Transect, Subregion)

# Density by region
mod_1 <- glm(n ~ year * Subregion, data = dens0, family = "poisson")

res <- emmeans(mod_1, specs = c("year"), by = "Subregion", type = "response")

as.tibble(res) %>%
  ggplot(aes(x = year, y = rate)) +
  facet_wrap(~Subregion) +
  geom_point() + #aes(color = Subregion)
  geom_errorbar(aes(ymin = rate - SE, ymax = rate + SE)) +
  geom_line(aes(group = 1)) + #aes(group = Subregion, color = Subregion
  geom_vline(aes(xintercept = "2014")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


# Overall density
# mod_1 <- glmer(n ~ year + (year|Subregion), data = dens0, family = "poisson",
#                verbose = TRUE, nAGQ=0, control=glmerControl(optimizer = "nloptwrap")) 
# anova(mod_1)
# 
# res <- emmeans(mod_1, specs = c("year"), type = "response")
# 
# as.tibble(res) %>%
#   ggplot(aes(x = year, y = rate)) +
#   geom_point() + #aes(color = Subregion)
#   geom_errorbar(aes(ymin = rate - SE, ymax = rate + SE)) +
#   geom_line(aes(group = 1)) + #aes(group = Subregion, color = Subregion
#   geom_vline(aes(xintercept = "2014")) +
#   theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

# Change in density 2014-2023 for each Species
```{r}
# Model change in density from 2014-2023 for each species
dens <- df %>%
  filter(year %in% c("2014", "2023")) %>%
  mutate(year = factor(year, levels = c("2023", "2014"))) %>%
  # Count number of colonies of each species per transect
  count(year, Species, Site, Transect, Subregion) %>%
  # Add zeros for all species not counted on a transect
  complete(Species, nesting(year, Site, Transect, Subregion), fill = list(n = 0)) %>%
  # SUBSET FOR FASTER MODELING
  group_by(Species, year) %>%
  filter(sum(n) >= 40) %>%
  ungroup()

mod5 <- glmer(n ~ Species * year + (1|Subregion), data = dens, family = "poisson",
              verbose = TRUE, nAGQ=0, control=glmerControl(optimizer = "nloptwrap")) 
anova(mod5)


diffs <- rbind(pairs(emmeans(mod5, specs = c("Species", "year")), by = "Species", level = 0.95))
saveRDS(diffs, file = "output/dens20142023.rds")
```

# Change in density 2014-2023 for each Subregion
```{r}
# Model change in density from 2014-2023 for each Subregion
dens <- df %>%
  filter(year %in% c("2014", "2023")) %>%
  mutate(year = factor(year, levels = c("2023", "2014"))) %>%
  # Count number of colonies of each species per transect
  count(year, Site, Transect, Subregion)

mod7 <- glm(n ~ Subregion * year, data = dens, family = "poisson") 
anova(mod7)
as_tibble(emmeans(mod7, specs = c("Subregion", "year"))) %>%
  ggplot(aes(x = year, y = emmean)) +
  geom_point() + geom_line() +
  facet_wrap(~Subregion)


diffs <- rbind(pairs(emmeans(mod7, specs = c("Subregion", "year")), by = "Subregion", level = 0.95))
saveRDS(diffs, file = "output/dens20142023subregions.rds")
```

#NMDS
```{r}
library(vegan)
dens <- df %>%
  filter(year %in% c("2014", "2015", "2023")) %>%
  mutate(year = factor(year, levels = c("2023", "2014", "2015"))) %>%
  # Count number of colonies of each species per transect
  count(year, Species, Site, Transect, Subregion) %>%
  # Add zeros for all species not counted on a transect
  complete(Species, nesting(year, Site, Transect, Subregion), fill = list(n = 0))

counts <- dens %>%
  pivot_wider(names_from = Species, values_from = n) %>%
  filter(Subregion %in% c("Biscayne", "Broward-Miami", "Lower Keys",
                          "Middle Keys", "Upper Keys", "Tortugas"))

nmds <- metaMDS(counts[,-(1:4)], distance = "bray")

out <- bind_cols(counts[,1:4], nmds$points)

out <- out %>%
  filter(MDS1 > -1000)

ggplot(out, aes(x = MDS1, y = MDS2, color = year, shape = year)) +
  geom_point(alpha = 0.5) +
  geom_point(data = cent, size = 5, alpha = 0.8) +
  facet_wrap(~Subregion)

cent <- out %>%
  group_by(Subregion, year) %>%
  summarize(MDS1 = median(MDS1),
            MDS2 = median(MDS2))

cent

biplot(nmds)
```

