---
title: "2023 DHW analysis for DRM survey locations"
output: html_document
date: "2024-05-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ncdf4) # package for netcdf manipulation
library(raster) # package for raster manipulation
library(tidyverse)
```

DHW data downloaded 5/1/24 using:
wget -r -l1 -A "ct*" https://www.star.nesdis.noaa.gov/pub/sod/mecb/crw/data/5km/v3.1_op/nc/v1.0/daily/dhw/2023/

netcdf tutorial here: https://rpubs.com/boyerag/297592

# 2023

```{r}
# Import all NetCDF files for each date from June 1 through December 31, 2023
nc.files <- list.files("data/dhw/2023", pattern = "*.nc$", full.names = TRUE)

# Get coordinate box for Florida Reef Tract
#nc <- nc_open("data/dhw/ct5km_dhw_v3.1_20230901.nc")
#nct <- ncvar_get(nc, "degree_heating_week", start = c(2000, 1240,1), count = c(21, 81,1))
# Longitude -83.525 --> index 1930
#nc$dim$lon$vals[2021]
# Longitude -78.975 --> index 2021
# Latitude 24 --> index 1321
#nc$dim$lat$vals[1240]
# Latitude 28 --> index 1240

# Get DRM survey site coordinates
# Import data
drmsites <- read_csv("data/drm/export.csv") %>%
  mutate(across(where(is.character), as_factor),
         Date = as_date(as.character(Date), format = "%m/%d/%Y")) %>%
  filter(year(Date) == "2023") %>%
  distinct(Site, Subregion, Longitude, Latitude)

# Open all DHW NCDF4 files
nc.data <- tibble(file = nc.files) %>%
  mutate(date = map_chr(file, ~str_extract(., "2023\\d+"), format = "%Y%m%d"),
         data = map(file, nc_open),
      dhw.all = map(data, ~ncvar_get(., "degree_heating_week", start = c(1930, 1240, 1), count = c(91, 81, 1))),
            r = map(dhw.all, ~raster(t(.), xmn = -83.525, xmx = -78.975, ymn = 23.975, ymx = 28.025,
                                     crs = CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs+ towgs84=0,0,0"))),
       coords = list(drmsites),
          dhw = map2(r, coords, ~raster::extract(.x, SpatialPoints(.y[,3:4]), method = "simple")))

out <- nc.data %>% dplyr::select(date, coords, dhw) %>% unnest() %>%
  mutate(date = as_date(date, format = "%Y%m%d"))

# Check that all sites got DHW values
dhws <- out %>%
  group_by(Site) %>%
  dplyr::summarize(avgdhw = mean(dhw))
nodhw <- dhws %>% filter(is.na(avgdhw))
nodhw
## 27 sites did not get DHW -- outside of 5km pixels (too close to land)

# Assign missing dhws value of closest site that has a dhw value
install.packages("FastKNN")
library(FastKNN)

# matrix of neighbours
n <- nrow(drmsites)
k <- 15 # Number of nearest neighbors to find
dm <- dist(drmsites[,3:4])
nn <- matrix(0,n,k) # n x k nearest neighbors matrix
for (i in 1:n) {
   nn[i,] = k.nearest.neighbors(i, as.matrix(dm), k = k)
}
nn[] <- as.character(drmsites$Site)[c(nn)]

# Get names of all sites and their nearest neighbors
neighbors <- as_tibble(cbind(Site = as.character(drmsites$Site), nn))
# Get dhws of all sites and dhws of their nearest neighbors
neighborsdhw <- neighbors %>%
  pivot_longer(-1, names_to = "nno", values_to = "nname") %>%
  mutate(nno = parse_number(nno) - 1) %>%
  mutate(navgdhw = dhws$avgdhw[match(nname, dhws$Site)])

finddhw <- neighborsdhw %>%
  filter(Site %in% nodhw$Site)

dhwmatch <- finddhw %>% 
  group_by(Site) %>%
  filter(!is.na(navgdhw)) %>%
  dplyr::summarize(closest_n_with_dhw = nname[nno == min(nno)]) %>%
  right_join(nodhw) %>%
  dplyr::select(1, 2) %>%
  print(n = nrow(.))
  
# Output matches
matches <- left_join(dhwmatch, drmsites)
range(matches$Longitude)
range(matches$Latitude)
matches2 <- left_join(dplyr::select(matches, Site = closest_n_with_dhw), drmsites) %>%
  distinct(Site, Longitude, Latitude)

# Plot matches
library(ggrepel)
ggplot(matches, aes(x = Longitude, y = Latitude)) +
  geom_point() +
  geom_point(data = matches2, color = "green") +
  geom_label_repel(data = matches2, aes(label = Site), color = "green", max.overlaps = 100, force = 80) +
  geom_label_repel(aes(label = Site), max.overlaps = 100, force = 80) +
  xlim(-80.125, -80) +
  ylim(26, 26.75)

# Replace missing dhws with values from matching sites
matches
fixing <- out %>%
  nest(data = c(date, dhw)) 

fixed <- fixing
### dhw data for sites where missing gets replaced with dhw data for the site of its closest neighbor site with dhw data
fixed[match(matches$Site, fixing$Site), "data"] <- fixing[match(matches$closest_n_with_dhw, fixing$Site), "data"]

### test if it worked (dhw was missing for site Y1048, should have been replaced with dhw data from Y1046)
fixing %>% filter(Site == "Y1048") %>% pull(data)
fixed %>% filter(Site == "Y1048") %>% pull(data)

identical(fixed$data[fixed$Site == "Y1048"], fixed$data[fixed$Site == "Y1046"])
y1 <- fixed$data[fixed$Site == "Y1048"][[1]]
y2 <- fixed$data[fixed$Site == "Y1046"][[1]]
cbind(y1, y2)

### test if it worked (dhw was missing for site Y1343, should have been replaced with dhw data from Y1346)
fixing %>% filter(Site == "Y1343") %>% pull(data)
fixed %>% filter(Site == "Y1343") %>% pull(data)

identical(fixed$data[fixed$Site == "Y1343"], fixed$data[fixed$Site == "Y1346"])
y1 <- fixed$data[fixed$Site == "Y1048"][[1]]
y2 <- fixed$data[fixed$Site == "Y1046"][[1]]
cbind(y1, y2)


# Unnest fixed output
outfixed <- fixed %>% unnest()
outfixed %>% filter(is.na(dhw))
```

```{r}
# Plot DHWs for all sites
ggplot(outfixed, aes(x = date, y = dhw, color = Subregion, group = Site)) +
  geom_line() +
  scale_x_date(date_breaks = "month", date_labels = "%b")
```

```{r}
# Write DHW data to file
write_csv(outfixed, file = "data/dhw/2023_dhw_processed.csv")
```


# 2015

```{r}
# Import all NetCDF files for each date from June 1 through December 31, 2015
nc.files <- list.files("data/dhw/2015", pattern = "*.nc$", full.names = TRUE)

# Get coordinate box for Florida Reef Tract
#nc <- nc_open("data/dhw/ct5km_dhw_v3.1_20230901.nc")
#nct <- ncvar_get(nc, "degree_heating_week", start = c(2000, 1240,1), count = c(21, 81,1))
# Longitude -83.525 --> index 1930
#nc$dim$lon$vals[2021]
# Longitude -78.975 --> index 2021
# Latitude 24 --> index 1321
#nc$dim$lat$vals[1240]
# Latitude 28 --> index 1240

# Get DRM survey site coordinates
# Import data
drmsites <- read_csv("data/drm/export.csv") %>%
  mutate(across(where(is.character), as_factor),
         Date = as_date(as.character(Date), format = "%m/%d/%Y")) %>%
  filter(year(Date) == "2015") %>%
  distinct(Site, Subregion, Longitude, Latitude)

# Open all DHW NCDF4 files
nc.data <- tibble(file = nc.files) %>%
  mutate(date = map_chr(file, ~str_extract(., "2015\\d+"), format = "%Y%m%d"),
         data = map(file, nc_open),
      dhw.all = map(data, ~ncvar_get(., "degree_heating_week", start = c(1930, 1240, 1), count = c(91, 81, 1))),
            r = map(dhw.all, ~raster(t(.), xmn = -83.525, xmx = -78.975, ymn = 23.975, ymx = 28.025,
                                     crs = CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs+ towgs84=0,0,0"))),
       coords = list(drmsites),
          dhw = map2(r, coords, ~raster::extract(.x, SpatialPoints(.y[,3:4]), method = "simple")))

out <- nc.data %>% dplyr::select(date, coords, dhw) %>% unnest() %>%
  mutate(date = as_date(date, format = "%Y%m%d"))

# Check that all sites got DHW values
dhws <- out %>%
  group_by(Site) %>%
  dplyr::summarize(avgdhw = mean(dhw))
nodhw <- dhws %>% filter(is.na(avgdhw))
nodhw
## 25 sites did not get DHW -- outside of 5km pixels (too close to land)

# Assign missing dhws value of closest site that has a dhw value
library(FastKNN)

# matrix of neighbours
n <- nrow(drmsites)
k <- 25 # Number of nearest neighbors to find
dm <- dist(drmsites[,3:4])
nn <- matrix(0,n,k) # n x k nearest neighbors matrix
for (i in 1:n) {
   nn[i,] = k.nearest.neighbors(i, as.matrix(dm), k = k)
}
nn[] <- as.character(drmsites$Site)[c(nn)]

# Get names of all sites and their nearest neighbors
neighbors <- as_tibble(cbind(Site = as.character(drmsites$Site), nn))
# Get dhws of all sites and dhws of their nearest neighbors
neighborsdhw <- neighbors %>%
  pivot_longer(-1, names_to = "nno", values_to = "nname") %>%
  mutate(nno = parse_number(nno) - 1) %>%
  mutate(navgdhw = dhws$avgdhw[match(nname, dhws$Site)])

finddhw <- neighborsdhw %>%
  filter(Site %in% nodhw$Site)

dhwmatch <- finddhw %>% 
  group_by(Site) %>%
  filter(!is.na(navgdhw)) %>%
  dplyr::summarize(closest_n_with_dhw = nname[nno == min(nno)]) %>%
  right_join(nodhw) %>%
  dplyr::select(1, 2) %>%
  print(n = nrow(.))
  
# Output matches
matches <- left_join(dhwmatch, drmsites)
range(matches$Longitude)
range(matches$Latitude)
matches2 <- left_join(dplyr::select(matches, Site = closest_n_with_dhw), drmsites) %>%
  distinct(Site, Longitude, Latitude)

# Plot matches
library(ggrepel)
ggplot(matches, aes(x = Longitude, y = Latitude)) +
  geom_point() +
  geom_point(data = matches2, color = "green") +
  geom_label_repel(data = matches2, aes(label = Site), color = "green", max.overlaps = 100, force = 80) +
  geom_label_repel(aes(label = Site), max.overlaps = 100, force = 80) +
  xlim(-80.125, -80) +
  ylim(26, 26.75)

# Replace missing dhws with values from matching sites
matches
fixing <- out %>%
  nest(data = c(date, dhw)) 

fixed <- fixing
### dhw data for sites where missing gets replaced with dhw data for the site of its closest neighbor site with dhw data
fixed[match(matches$Site, fixing$Site), "data"] <- fixing[match(matches$closest_n_with_dhw, fixing$Site), "data"]

### test if it worked (dhw was missing for site O1020, should have been replaced with dhw data from O2015)
fixing %>% filter(Site == "O1020") %>% pull(data)
fixed %>% filter(Site == "O2015") %>% pull(data)

identical(fixed$data[fixed$Site == "O1020"], fixed$data[fixed$Site == "O2015"])
y1 <- fixed$data[fixed$Site == "O1020"][[1]]
y2 <- fixed$data[fixed$Site == "O2015"][[1]]
cbind(y1, y2)



# Unnest fixed output
outfixed <- fixed %>% unnest()
outfixed %>% filter(is.na(dhw))
```

```{r}
# Plot DHWs for all sites
ggplot(outfixed, aes(x = date, y = dhw, color = Subregion, group = Site)) +
  geom_line() +
  scale_x_date(date_breaks = "month", date_labels = "%b")
```

```{r}
# Write DHW data to file
write_csv(outfixed, file = "data/dhw/2015/2015_dhw_processed.csv")
```


# 2014
```{r}
# Import all NetCDF files for each date from June 1 through December 31, 2015
nc.files <- list.files("data/dhw/2014", pattern = "*.nc$", full.names = TRUE)

# Get coordinate box for Florida Reef Tract
#nc <- nc_open("data/dhw/ct5km_dhw_v3.1_20230901.nc")
#nct <- ncvar_get(nc, "degree_heating_week", start = c(2000, 1240,1), count = c(21, 81,1))
# Longitude -83.525 --> index 1930
#nc$dim$lon$vals[2021]
# Longitude -78.975 --> index 2021
# Latitude 24 --> index 1321
#nc$dim$lat$vals[1240]
# Latitude 28 --> index 1240

# Get DRM survey site coordinates
# Import data
drmsites <- read_csv("data/drm/export.csv") %>%
  mutate(across(where(is.character), as_factor),
         Date = as_date(as.character(Date), format = "%m/%d/%Y")) %>%
  filter(year(Date) == "2014") %>%
  distinct(Site, Subregion, Longitude, Latitude)

# Open all DHW NCDF4 files
nc.data <- tibble(file = nc.files) %>%
  mutate(date = map_chr(file, ~str_extract(., "2014\\d+"), format = "%Y%m%d"),
         data = map(file, nc_open),
      dhw.all = map(data, ~ncvar_get(., "degree_heating_week", start = c(1930, 1240, 1), count = c(91, 81, 1))),
            r = map(dhw.all, ~raster(t(.), xmn = -83.525, xmx = -78.975, ymn = 23.975, ymx = 28.025,
                                     crs = CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs+ towgs84=0,0,0"))),
       coords = list(drmsites),
          dhw = map2(r, coords, ~raster::extract(.x, SpatialPoints(.y[,3:4]), method = "simple")))

out <- nc.data %>% dplyr::select(date, coords, dhw) %>% unnest() %>%
  mutate(date = as_date(date, format = "%Y%m%d"))

# Check that all sites got DHW values
dhws <- out %>%
  group_by(Site) %>%
  dplyr::summarize(avgdhw = mean(dhw))
nodhw <- dhws %>% filter(is.na(avgdhw))
nodhw
## 13 sites did not get DHW -- outside of 5km pixels (too close to land)

# Assign missing dhws value of closest site that has a dhw value
library(FastKNN)

# matrix of neighbours
n <- nrow(drmsites)
k <- 25 # Number of nearest neighbors to find
dm <- dist(drmsites[,3:4])
nn <- matrix(0,n,k) # n x k nearest neighbors matrix
for (i in 1:n) {
   nn[i,] = k.nearest.neighbors(i, as.matrix(dm), k = k)
}
nn[] <- as.character(drmsites$Site)[c(nn)]

# Get names of all sites and their nearest neighbors
neighbors <- as_tibble(cbind(Site = as.character(drmsites$Site), nn))
# Get dhws of all sites and dhws of their nearest neighbors
neighborsdhw <- neighbors %>%
  pivot_longer(-1, names_to = "nno", values_to = "nname") %>%
  mutate(nno = parse_number(nno) - 1) %>%
  mutate(navgdhw = dhws$avgdhw[match(nname, dhws$Site)])

finddhw <- neighborsdhw %>%
  filter(Site %in% nodhw$Site)

dhwmatch <- finddhw %>% 
  group_by(Site) %>%
  filter(!is.na(navgdhw)) %>%
  dplyr::summarize(closest_n_with_dhw = nname[nno == min(nno)]) %>%
  right_join(nodhw) %>%
  dplyr::select(1, 2) %>%
  print(n = nrow(.))
  
# Output matches
matches <- left_join(dhwmatch, drmsites)
range(matches$Longitude)
range(matches$Latitude)
matches2 <- left_join(dplyr::select(matches, Site = closest_n_with_dhw), drmsites) %>%
  distinct(Site, Longitude, Latitude)

# Plot matches
library(ggrepel)
ggplot(matches, aes(x = Longitude, y = Latitude)) +
  geom_point() +
  geom_point(data = matches2, color = "green") +
  geom_label_repel(data = matches2, aes(label = Site), color = "green", max.overlaps = 100, force = 80) +
  geom_label_repel(aes(label = Site), max.overlaps = 100, force = 80) +
  xlim(-80.125, -80) +
  ylim(26, 26.75)

# Replace missing dhws with values from matching sites
matches
fixing <- out %>%
  nest(data = c(date, dhw)) 

fixed <- fixing
### dhw data for sites where missing gets replaced with dhw data for the site of its closest neighbor site with dhw data
fixed[match(matches$Site, fixing$Site), "data"] <- fixing[match(matches$closest_n_with_dhw, fixing$Site), "data"]

### test if it worked (dhw was missing for site O1020, should have been replaced with dhw data from O2015)
fixing %>% filter(Site == "O1020") %>% pull(data)
fixed %>% filter(Site == "O2015") %>% pull(data)

identical(fixed$data[fixed$Site == "O1020"], fixed$data[fixed$Site == "O2015"])
y1 <- fixed$data[fixed$Site == "O1020"][[1]]
y2 <- fixed$data[fixed$Site == "O2015"][[1]]
cbind(y1, y2)



# Unnest fixed output
outfixed <- fixed %>% unnest()
outfixed %>% filter(is.na(dhw))
```

```{r}
# Plot DHWs for all sites
ggplot(outfixed, aes(x = date, y = dhw, color = Subregion, group = Site)) +
  geom_line() +
  scale_x_date(date_breaks = "month", date_labels = "%b")
```

```{r}
# Write DHW data to file
write_csv(outfixed, file = "data/dhw/2014/2014_dhw_processed.csv")
```
