---
title: "binning locations across years"
author: "R. Cunning"
date: "2024-05-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
# Load all data from 2014, 2015, 2022, and 2023
# QC'd by year
load("output/2014.RData")
df14 <- df14 %>% filter(!Subregion %in% c("Martin", "North Palm Beach"))
load("output/2015.RData")
load("output/2022.RData")
load("output/2023.RData")
df23 <- df23 %>% rename(Depth = EndDepth, Transect = TransectNum)
all0 <- bind_rows(
  `2014` = df14,
  `2015` = df15,
  `2022` = df22,
  `2023` = df23,
  .id = "year"
) %>%
  mutate(dhw.bin = cut(dhw, breaks = c(-1, 3, 6, 9, 12, 15, 18, 22)))

sites <- all0 %>%
  distinct(year, Subregion, Zone, Latitude, Longitude, Site)

# test <- sites %>%
#   #group_by(Subregion) %>%
#   #filter(n() > 3) %>%
#   nest() %>%
#   mutate(dist = map(data, ~dist(.[,c("Longitude", "Latitude")])),
#            hc = map(dist, ~hclust(.)),
#         clust = map(hc, ~cutree(hc, k = 50)))

dist <- dist(sites[,c("Longitude", "Latitude")])
hc <- hclust(dist)
plot(hc)
clust <- cutree(hc, k = 50)

sites <- sites %>%
  mutate(clust = clust)

sites %>%
  #filter(Subregion == "Broward-Miami") %>%
  ggplot(aes(x = Longitude, y = Latitude, color = factor(clust))) +
  #geom_point() +
  geom_text(aes(label = clust)) +
  facet_wrap(~Subregion, scales = "free") +
  theme(legend.position = "none")
  

all0 <- left_join(all0, sites)

res <- all0 %>%
  group_by(year, clust, Subregion) %>%
  summarize(BL = sum(Bleaching2 > 1),
            NB = sum(Bleaching2 <= 1),
            pctBL = BL / (NB + BL))

res2 <- res %>% 
  dplyr::select(clust, Subregion, year, pctBL) %>%
  pivot_wider(names_from = year, values_from = pctBL)

library(GGally)
res2 %>%
  ungroup() %>%
  dplyr::select(3:6) %>%
  #filter(Subregion == "Broward-Miami") %>%
  droplevels() %>%
  ggpairs()


ggplot(res2, aes(x = pc))

ggplot(res, aes(x = year, y = pctBL)) +
  geom_boxplot() +
  facet_wrap(~Subregion)
```


```{r}
# Subset only peak bleaching for each year

peak0 <- all0 %>%
  filter((Date > "2014-08-20" & Date < "2014-10-15") |
         (Date > "2015-09-01" & Date < "2015-10-05") |
         (Date > "2022-09-15" & Date < "2022-10-30") |
         (Date > "2023-08-01" & Date < "2023-10-01"))

res <- peak0 %>%
  group_by(year, clust, Subregion) %>%
  summarize(BL = sum(Bleaching2 > 1),
            NB = sum(Bleaching2 <= 1),
            pctBL = BL / (NB + BL))

ggplot(res, aes(x = year, y = pctBL)) +
  geom_boxplot() +
  facet_wrap(~Subregion)


res2 <- res %>% 
  dplyr::select(clust, Subregion, year, pctBL) %>%
  pivot_wider(names_from = year, values_from = pctBL)

library(GGally)
res2 %>%
  ungroup() %>%
  dplyr::select(3:6) %>%
  #filter(Subregion == "Broward-Miami") %>%
  droplevels() %>%
  ggpairs()
```


```{r}
test <- peak0 %>%
  group_by(year, clust, Site, dhw, Subregion) %>%
  summarize(BL = sum(Bleaching2 > 1),
            NB = sum(Bleaching2 <= 1),
            pctBL = BL / (NB + BL)) %>%
  group_by(year, clust, Subregion) %>%
  summarize(meanpctBL = mean(pctBL),
            meandhw = mean(dhw)) %>%
  mutate(pctBL.dhw = log(meanpctBL / meandhw))


test2 <- test %>% 
  dplyr::select(Subregion, clust, year, pctBL.dhw) %>%
  pivot_wider(names_from = year, values_from = pctBL.dhw)

library(GGally)
test2 %>%
  ungroup() %>%
  dplyr::select(3:6) %>%
  #filter(Subregion == "Broward-Miami") %>%
  droplevels() %>%
  ggpairs()
```


```{r}
mydf <- all0 %>%
  filter(Transect %in% c(1, 2)) %>%   # because only 2023 has 3 and 4
  group_by(year, Site, Subregion, dhw, Week2) %>%
  summarize(BL = sum(Bleaching2 > 1),
            NB = sum(Bleaching2 <= 1))

ggplot(mydf, aes(x = dhw, y = BL / (NB + BL), color = year)) + 
  geom_point() + 
  geom_smooth(aes(group = year))

mod <- glm(cbind(BL, NB) ~ year * dhw + year:Week2, family = "binomial", data = mydf)

# Get residuals (raw residuals = difference between observed and predicted bleaching probability)
res <- tibble(mydf, .resid = residuals(mod, type = "response"))

# Cluster sites
sites <- all0 %>%
  distinct(year, Subregion, Zone, Latitude, Longitude, Site)
dist <- dist(sites[,c("Longitude", "Latitude")])
hc <- hclust(dist)

# Choose how many cluster and assign cluster ids to each site
sites <- sites %>%
  mutate(clust = cutree(hc, k = 250))

# Join cluster ids with residuals
res2 <- res %>%
  left_join(sites)

# Get mean residuals for each cluster in each year
res2 <- res2 %>%
  group_by(year, clust) %>%
  summarize(meanresid = mean(.resid)) %>%
  pivot_wider(names_from = year, values_from = meanresid)

ggpairs(res2, columns = 2:5,
        lower=list(continuous="smooth"))
```

```{r}
# Model proportion of bleached colonies in each subregion in each 2-week window of survey
mod <- glm(cbind(BL, NB) ~ Subregion * year * Week2, family = "binomial", data = mydf)

# Predict proportion of bleached colonies in each Subregion at weeks 34-35 (Week2 = "(33,35]" => (August 20-September 2))) = peak of bleaching
## Get these Subregion probabilities at this time on the log-odds scale (NOT type = 'response')
res <- emmeans(mod, specs = c("Subregion", "Week2", "year"))
res <- as.tibble(res) %>%
  filter((year == "2014" & Week2 == "(36,38]") |
         (year == "2015" & Week2 == "(36,38]") |
         (year == "2022" & Week2 == "(38,40]") |
         (year == "2023" & Week2 == "(33,35]"))

# Get residuals for each Site at the time it was surveyed (e.g., difference from Subregion mean at time surveyed)...
# ...and then add these residuals to the Subregion's predicted bleaching probability at peak of bleaching
# ...to get predicted bleaching severity at that site, if it had been surveyed at peak of bleaching
mydf.adj <- mydf %>%
  ungroup() %>%
  # Get residuals on the 'working' /logit scale
  mutate(resid = residuals(mod, type = "working")) %>%
  # Join site residuals with logit means for Subregion at peak weeks
  left_join(as_tibble(res), by = c("year", "Subregion")) %>%
  # Add residuals to logit mean for Subregion peak weeks, then convert to probability scale
  mutate(adj = emmean + resid,
         ## Function to convert logit to probability
         adjprob = exp(adj) / (1 + exp(adj))) %>%
  mutate(n = BL + NB)


mod <- glm(adjprob ~ year * dhw, weights = n, family = "quasibinomial", data = mydf.adj)

# Get residuals (raw residuals = difference between observed and predicted bleaching probability)
resid <- residuals(mod, type = "response")
res <- bind_cols(drop_na(mydf.adj), resid)

# Cluster sites
sites <- all0 %>%
  distinct(year, Subregion, Zone, Latitude, Longitude, Site)
dist <- dist(sites[,c("Longitude", "Latitude")])
hc <- hclust(dist)

# Choose how many cluster and assign cluster ids to each site
sites <- sites %>%
  mutate(clust = cutree(hc, k = 100))

# Join cluster ids with residuals
res2 <- res %>%
  left_join(sites)

# Get mean residuals for each cluster in each year
res2 <- res2 %>%
  group_by(year, clust) %>%
  summarize(meanresid = mean(resid)) %>%
  pivot_wider(names_from = year, values_from = meanresid)

ggpairs(res2, columns = 2:5,
        lower=list(continuous="smooth"))
```

