---
title: "2_DRM_processing"
author: "R. Cunning"
date: "2025-02-13"
output: html_document
---

```{r}
library(tidyverse)
```


# 2014

### 2014 DRM data
```{r 2014_drm}
# Import DRM data
df <- read_csv("data/drm/export.csv") %>%
  mutate(across(where(is.character), as_factor),
         Date = as_date(as.character(Date), format = "%m/%d/%Y"))

# Get day of the year number, week, and month for some model fitting
df <- df %>%
  mutate(Day = yday(Date),
         Week = week(Date),
         Week2 = factor(cut(Week, breaks = seq(0,52,2))),
         Week = factor(Week),
         Month = factor(month(Date)))

# Subset just 2014 surveys
df14 <- filter(df, year(Date) == "2014")
# How many corals observed?
nrow(df14)

# Change Deerfield to either Broward or South Palm Beach based on Lat = 26.32825
df14[df14$Subregion == "Deerfield" & df14$Latitude > 26.32825, "Subregion"] <- "South Palm Beach"
df14[df14$Subregion == "Deerfield" & df14$Latitude < 26.32825, "Subregion"] <- "Broward-Miami"

# Order Subregions from south to north
df14 <- df14 %>%
  mutate(Subregion = fct_relevel(Subregion, c("Tortugas--Dry Tortugas NP", "Marquesas", "Lower Keys", 
                                              "Middle Keys", "Mid-Upper Keys Transition", "Upper Keys",
                                              "Biscayne", "Broward-Miami", "South Palm Beach", 
                                              "North Palm Beach", "Martin")))

# Order Species alphabetically
df14 <- df14 %>%
  mutate(Species = factor(Species, levels = sort(levels(df$Species))))

# Are there any dead corals?
# dead <- df14 %>% filter(Old + Recent >= 100)
# There are recently dead corals that do not have the TRS code -- assume these ARE dead from thermal stress and add TRS code. SCTLD had only just started to be detected in Miami, and almost all of these "dead" corals were in the Keys so highly unlikely that mortality was due to disease. Therefore, assign TRS and assume these died from bleaching
#df14[df14$Recent == 100 & !grepl("TRS", df14$`Other Conditions`), "Other Conditions"] <- "TRS"
df14[(df14$Recent + df14$Old) >= 100 & !grepl("TRS", df14$`Other Conditions`), "Other Conditions"] <- "TRS"
# Remove other completely dead corals (Old Mort)
# df14 <- df14 %>%
#   filter(!((Old + Recent) >= 100 & !grepl("TRS", `Other Conditions`)))

# Create ordinal variables and factors for bleaching severity
df14 <- df14 %>%
  mutate(Bleaching2 = case_when((is.na(Bleaching) & !grepl("TRS", `Other Conditions`)) ~ 0,
                                Bleaching == "P" ~ 1,
                                Bleaching == "PB" ~ 2,
                                Bleaching == "BL" ~ 3,
                                ((Old + Recent) >= 100 & grepl("TRS", `Other Conditions`)) ~ 4),
         Bleaching3 = factor(case_match(Bleaching2, 
                                 0 ~ "Healthy",
                                 1 ~ "Pale",
                                 2 ~ "Partially Bleached",
                                 3 ~ "Bleached",
                                 4 ~ "Dead"),
                             levels = c("Healthy", "Pale", "Partially Bleached", "Bleached", "Dead")))

dead <- df14 %>%
  filter(Bleaching3 == "Dead")
```

### 2014 DHW data
```{r 2014_dhw}
# Import 2014 DHW data
dhw <- read_csv("data/processed/2014_dhw_processed.csv") %>%
  mutate(across(where(is.character), as_factor)) %>%
  rename(Date = date) %>%
  dplyr::select(Site, Date, dhw)

# Get max. DHW value for on OR BEFORE date surveyed
dhw <- dhw %>%
  group_by(Site) %>%
  mutate(cummaxdhw = cummax(dhw))

# Get DHW values for each DRM survey site on the date surveyed -- join with DRM data
df14 <- left_join(df14, dhw, by = c("Site", "Date"), keep = FALSE)

# Get peak DHW values for each site (weeks 36-38) regardless of when surveyed)
peakdhw <- dhw %>%
  mutate(Week2 = factor(cut(week(Date), breaks = seq(0,52,2)))) %>%
  filter(Week2 == "(36,38]") %>%
  group_by(Site) %>%
  summarize(peakdhw = max(dhw))
df14 <- left_join(df14, peakdhw)
```

### Save 2014 processed data
```{r 2014_save}
save(df14, file = "data/processed/2014.RData")
```

# 2015

### 2015 DRM data
```{r 2015_drm}
# Import DRM data
df <- read_csv("data/drm/export.csv") %>%
  mutate(across(where(is.character), as_factor),
         Date = as_date(as.character(Date), format = "%m/%d/%Y"))

# Get day of the year number, week, and month for some model fitting
df <- df %>%
  mutate(Day = yday(Date),
         Week = week(Date),
         Week2 = factor(cut(Week, breaks = seq(0,52,2))),
         Week = factor(Week),
         Month = factor(month(Date)))

# Subset just 2015 surveys
df15 <- filter(df, year(Date) == "2015")
# How many corals observed?
nrow(df15)

# Change Deerfield to either Broward or South Palm Beach based on Lat = 26.32825
df15[df15$Subregion == "Deerfield" & df15$Latitude > 26.32825, "Subregion"] <- "South Palm Beach"
df15[df15$Subregion == "Deerfield" & df15$Latitude < 26.32825, "Subregion"] <- "Broward-Miami"

# Order Subregions from south to north
df15 <- df15 %>%
  mutate(Subregion = fct_relevel(Subregion, c("Tortugas--Dry Tortugas NP", "Marquesas", "Lower Keys", 
                                              "Middle Keys", "Mid-Upper Keys Transition", "Upper Keys",
                                              "Biscayne", "Broward-Miami", "South Palm Beach", 
                                              "North Palm Beach", "Martin")))

# Order Species alphabetically
df15 <- df15 %>%
  mutate(Species = factor(Species, levels = sort(levels(df$Species))))

# Are there any dead corals?
# dead <- df15 %>% filter(Old + Recent >= 100)
# There are recently dead corals -- but this could have been SCTLD, in Biscayne up to Palm Beach....
# Assign dead corals NOT in those regions TRS (dead from bleaching)
df15[(df15$Old + df15$Recent) >= 100 & !df15$Subregion %in% c("Biscayne", "Broward-Miami", "South Palm Beach"), "Other Conditions"] <- "TRS"
# Remove other dead corals (likely disease death)
df15 <- df15 %>%
  filter(((Old + Recent < 100) | grepl("TRS", `Other Conditions`)))

# Create ordinal variables and factors for bleaching severity
df15 <- df15 %>%
  mutate(Bleaching2 = case_when((is.na(Bleaching) & !grepl("TRS", `Other Conditions`)) ~ 0,
                                Bleaching == "P" ~ 1,
                                Bleaching == "PB" ~ 2,
                                Bleaching == "BL" ~ 3,
                                ((Old + Recent) >= 100 & grepl("TRS", `Other Conditions`)) ~ 4),
         Bleaching3 = factor(case_match(Bleaching2, 
                                 0 ~ "Healthy",
                                 1 ~ "Pale",
                                 2 ~ "Partially Bleached",
                                 3 ~ "Bleached",
                                 4 ~ "Dead"),
                             levels = c("Healthy", "Pale", "Partially Bleached", "Bleached", "Dead")))
```

### 2015 DHW data
```{r 2015_dhw}
# Import 2015 DHW data
dhw <- read_csv("data/processed/2015_dhw_processed.csv") %>%
  mutate(across(where(is.character), as_factor)) %>%
  rename(Date = date) %>%
  dplyr::select(Site, Date, dhw)

# Get max. DHW value for on OR BEFORE date surveyed
dhw <- dhw %>%
  group_by(Site) %>%
  mutate(cummaxdhw = cummax(dhw))

# Get DHW values for each DRM survey site on the date surveyed -- join with DRM data
df15 <- left_join(df15, dhw, by = c("Site", "Date"))

# Get peak DHW values for each site (weeks 36-38) regardless of when surveyed)
peakdhw <- dhw %>%
  mutate(Week2 = factor(cut(week(Date), breaks = seq(0,52,2)))) %>%
  filter(Week2 == "(36,38]") %>%
  group_by(Site) %>%
  summarize(peakdhw = max(dhw))
df15 <- left_join(df15, peakdhw)

# ggplot(df15, aes(x = dhw, y = peakdhw, color = Subregion)) + geom_point()
```

### Save 2015 processed data
```{r 2015_save}
save(df15, file = "data/processed/2015.RData")
```

# 2023

### 2023 DRM data
```{r 2023_drm}
# Import Transect 1 and 2 data
t1t2 <- readxl::read_xlsx("data/drm/Updated_2023AfterQAQC_RawCoralDataTransect1and2.xlsx",
                          na = "NULL")

# Import Transect 3 and 4 data
t3t4 <- readxl::read_xlsx("data/drm/Updated_2023AfterQAQC_RawCoralDataTransects3and4.xlsx")

# Combine
df <- bind_rows(t1t2, t3t4)
# How many corals observed?
nrow(df)

# Recode and rename things
df <- df %>%
  mutate(Bleaching = case_match(
    Bleaching, 
    "Not Bleached" ~ NA,
    "Pale" ~ "P",
    "Partly Bleached" ~ "PB",
    "Totally Bleached" ~ "BL",
    )) %>%
  rename(Old = OldMortality, Recent = RecentMortality,
         `Other Conditions` = oCondition) %>%
  mutate(across(where(is.character), as_factor),
         Date = as_date(as.character(Date), format = "%Y-%m-%d"))

# Get day of the year number, week, and month for some model fitting
df <- df %>%
  mutate(Day = yday(Date),
         Week = week(Date),
         Week2 = factor(cut(Week, breaks = seq(1,52,2))),
         Week = factor(Week),
         Month = factor(month(Date)))

# Subset just 2023 surveys
df23 <- filter(df, year(Date) == "2023")
# Subset at some earlier date? Later in the season, corals are probably dead and not counted, underestimating bleaching and mortality rates...?
# df23 <- filter(df23, Date < "2023-10-01")


# Order Subregions from south to north
df23 <- df23 %>%
  mutate(Subregion = fct_relevel(Subregion, c("Tortugas--Dry Tortugas NP", "Marquesas", "Lower Keys", 
                                              "Middle Keys", "Mid-Upper Keys Transition", "Upper Keys",
                                              "Biscayne", "Broward-Miami", "South Palm Beach", 
                                              "North Palm Beach", "Martin")))

# Order Species alphabetically
df23 <- df23 %>%
  mutate(Species = factor(Species, levels = sort(levels(df$Species))))

# Dead corals
dead <- df23 %>%
  filter((Old + Recent) >= 100)
## 324 of the dead corals do have TRS code, 24 do not -- assume these ARE also dead from thermal stress and add TRS code
# table(grepl("TRS", dead$`Other Conditions`))
df23 <- df23 %>%
  mutate(`Other Conditions` = case_when((Old + Recent >= 100) ~ "TRS",
                                        TRUE ~ `Other Conditions`))



# Create ordinal variables and factors for bleaching severity
df23 <- df23 %>%
  mutate(Bleaching2 = case_when((is.na(Bleaching) & !grepl("TRS", `Other Conditions`)) ~ 0,
                                Bleaching == "P" ~ 1,
                                Bleaching == "PB" ~ 2,
                                Bleaching == "BL" ~ 3,
                                ((Old + Recent) >= 100 & grepl("TRS", `Other Conditions`)) ~ 4),
         Bleaching3 = factor(case_match(Bleaching2, 
                                 0 ~ "Healthy",
                                 1 ~ "Pale",
                                 2 ~ "Partially Bleached",
                                 3 ~ "Bleached",
                                 4 ~ "Dead"),
                             levels = c("Healthy", "Pale", "Partially Bleached", "Bleached", "Dead")))


# # There are corals with the TRS code that are NOT fully dead, but don't have BL code
test <- df23 %>% filter(is.na(Bleaching2))
#### Filter these out
df23 <- df23 %>%
  filter(!is.na(Bleaching2))
```

### 2023 DHW data
```{r 2023_dhw}
# Import 2023 DHW data
dhw <- read_csv("data/processed/2023_dhw_processed.csv") %>%
  mutate(across(where(is.character), as_factor)) %>%
  rename(Date = date) %>%
  dplyr::select(Site, Date, dhw)

# Get max DHW experienced in 2023 for each site as of the date surveyed?
# or something like cumulative DHW? I think there are lots of corals that already bleached and died by September onward that are not getting captured in the surveys...

# Get max. DHW value for on OR BEFORE date surveyed
dhw <- dhw %>%
  group_by(Site) %>%
  mutate(cummaxdhw = cummax(dhw))
  

# Get DHW values for each DRM survey site on the date surveyed -- join with DRM data
df23 <- left_join(df23, dhw, by = c("Site", "Date"))


# Get peak DHW values for each site (weeks 36-38) regardless of when surveyed)
peakdhw <- dhw %>%
  mutate(Week2 = factor(cut(week(Date), breaks = seq(1,52,2)))) %>%
  filter(Week2 == "(33,35]") %>%
  group_by(Site) %>%
  summarize(peakdhw = max(dhw))
df23 <- left_join(df23, peakdhw)
ggplot(df23, aes(x = dhw, y = peakdhw, color = Subregion)) + geom_point()
```

### Save 2023 processed data
```{r}
# Remove rows where Species is NA (transects 3 and 4 when nothing was observed)
df23 <- df23 %>%
  filter(!is.na(Species))
df23 %>%
  count(TransectNum)
save(df23, file = "data/processed/2023.RData")
```

# 2024

### 2024 DRM data
```{r 2024_DRM}
# Transect 1 and 2 data
t1t2 <- read_csv("data/drm/FRRP_EXPORT.csv") %>%
  mutate(across(where(is.character), as_factor),
         Date = as_date(as.character(Date), format = "%m/%d/%Y %H:%M:%S")) %>%
  rename(Depth = Enddepth, TLRate = Tlrate,
         `Disease Conditions` = Disease_Conditions, 
         `Other Conditions` = Other_Conditions,
         oPercRecMort = Opercrecmort, 
         dPercRecMort = Dpercrecmort)
# Subset just 2024 surveys
t1t2 <- filter(t1t2, year(Date) == "2024") %>% droplevels()
# How many corals observed?
nrow(t1t2)

# Transect 3 and 4 data
t3t4 <- readxl::read_xlsx("data/drm/2024ANU_RawCoralDataTransect3and4_QAQC.xlsx") %>%
  mutate(Date = as_date(as.character(Date))) %>%
  rename(Depth = EndDepth,
         Old = OldMortality, Recent = RecentMortality,
         `Disease Conditions` = dCondition, `Other Conditions` = oCondition,
         oPercRecMort = OtherRecentMortality,
         dPercRecMort = DiseaseRecentMoratlity,
         Transect = TransectNum)
nrow(t3t4)

df24 <- bind_rows(t1t2, t3t4) %>%
   mutate(Bleaching = case_match(
    Bleaching, 
    "Not Bleached" ~ NA,
    "Pale" ~ "P",
    "Partly Bleached" ~ "PB",
    "Totally Bleached" ~ "BL",
    ))
names(df24)

# Get day of the year number, week, and month for some model fitting
df24 <- df24 %>%
  mutate(Day = yday(Date),
         Week = week(Date),
         Week2 = factor(cut(Week, breaks = seq(0,52,2))),
         Week = factor(Week),
         Month = factor(month(Date)))
nrow(df24)


# unique(df24$Subregion)
# df24 %>% filter(Subregion == "Marquesas-Tortugas Trans")
# unique(df23$Subregion)
# 
# ggplot(df23, aes(x = Longitude, y = Latitude, color = Subregion)) +
#   geom_point() + ggtitle("2023")
# ggplot(df24, aes(x = Longitude, y = Latitude, color = Subregion)) +
#   geom_point() + ggtitle("2024")


# Order Subregions from south to north
df24 <- df24 %>%
  mutate(Subregion = fct_relevel(Subregion, c("Tortugas--Tortugas Bank", "Tortugas--Dry Tortugas NP",
                                              "Marquesas", "Lower Keys", 
                                              "Middle Keys", "Mid-Upper Keys Transition", "Upper Keys",
                                              "Biscayne", "Broward-Miami", "South Palm Beach", 
                                              "North Palm Beach", "Martin")))

# Order Species alphabetically
df24 <- df24 %>%
  mutate(Species = factor(Species, levels = sort(levels(df$Species))))

# Are there any dead corals?
dead <- df24 %>% filter(Old + Recent >= 100)
dead
# There are 9 recently dead corals -- they have OUK, OGI, or SC conditions -- remove these from dataset
df24 <- anti_join(df24, dead)

# Create ordinal variables and factors for bleaching severity
df24 <- df24 %>%
  mutate(Bleaching2 = case_when((is.na(Bleaching) & !grepl("TRS", `Other Conditions`)) ~ 0,
                                Bleaching == "P" ~ 1,
                                Bleaching == "PB" ~ 2,
                                Bleaching == "BL" ~ 3,
                                ((Old + Recent) >= 100 & grepl("TRS", `Other Conditions`)) ~ 4),
         Bleaching3 = factor(case_match(Bleaching2, 
                                 0 ~ "Healthy",
                                 1 ~ "Pale",
                                 2 ~ "Partially Bleached",
                                 3 ~ "Bleached",
                                 4 ~ "Dead"),
                             levels = c("Healthy", "Pale", "Partially Bleached", "Bleached", "Dead")))


# There are some corals with TRS but no BL condition recorded, unsure how to treat
df24 %>% filter(grepl("TRS", `Other Conditions`))


```

### 2024 DHW data
```{r 2024_dhw}
# Import 2024 DHW data
dhw <- read_csv("data/processed/2024_dhw_processed.csv") %>%
  mutate(across(where(is.character), as_factor)) %>%
  rename(Date = date) %>%
  dplyr::select(Site, Date, dhw)


# Get max DHW experienced in 2024 for each site as of the date surveyed?
# or something like cumulative DHW? I think there are lots of corals that already bleached and died by September onward that are not getting captured in the surveys...

# Get max. DHW value for on OR BEFORE date surveyed
dhw <- dhw %>%
  group_by(Site) %>%
  mutate(cummaxdhw = cummax(dhw))
  

# Get DHW values for each DRM survey site on the date surveyed -- join with DRM data
df24 <- left_join(df24, dhw, by = c("Site", "Date"))


# Get peak DHW values for each site (weeks 36-38) regardless of when surveyed)
peakdhw <- dhw %>%
  mutate(Week2 = factor(cut(week(Date), breaks = seq(1,52,2)))) %>%
  filter(Week2 == "(39,41]") %>%
  group_by(Site) %>%
  summarize(peakdhw = max(dhw))
df24 <- left_join(df24, peakdhw)
ggplot(df24, aes(x = dhw, y = cummaxdhw, color = Subregion)) + geom_point()
```

### Save 2024 processed data
```{r}
# Remove rows where Species is NA (transects 3 and 4 when nothing was observed)
df24 <- df24 %>%
  filter(!is.na(Species))
df24 %>%
  count(Transect)
save(df24, file = "data/processed/2024.RData")
```
